on:
  push:
    branches:
      - master
name: main
jobs:
  # release-pr:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: google-github-actions/release-please-action@v2
  #       id: release-please
  #       with:
  #         path: packages/one
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         release-type: node
  #         package-name: one
  #         monorepo-tags: true
  #         command: release-pr
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: tag-release
        with:
          path: packages/one
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          # monorepo-tags: true
          # package-name: one
          command: manifest
      - uses: actions/checkout@v2
        if: ${{ steps.tag-release.outputs.releases_created }}
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps.tag-release) }}
        run: echo "$STEPS_CONTEXT"
      - name: ONE
        if: ${{ steps.tag-release.outputs.one--release_created }}
        run: echo "one"
      - name: TWO
        if: ${{ steps.tag-release.outputs.two--release_created }}
        run: echo "two"
