on:
  push:
    branches:
      - master
name: release
jobs:
  changeFinder:
    runs-on: ubuntu-latest
    outputs:
      nodePaths: ${{ steps.interrogate.outputs.nodePaths }}
    steps:
      - uses: actions/checkout@v2
      - id: interrogate
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const {execSync} = require('child_process');
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
            const latestRelease = await github.repos.getLatestRelease({
              owner,
              repo
            });
            console.log(`latest release: ${JSON.stringify(latestRelease.data)}`);
            execSync('git pull --tags');
            execSync(`git reset --hard ${latestRelease.data.tag_name}`);
            const status = execSync(`git diff --name-only origin/master`, { encoding: 'utf-8'});
            console.log(status);
            const changes = status.split('\n');
            let nodePaths = new Set();
            for (const change of changes) {
              if (change.startsWith('packages/')) {
                  console.log(change)
                  const library = change.split('/')[1];
                  nodePaths.add(library);
              };
            }
            nodePaths = Array.from(nodePaths);
            console.log(`${JSON.stringify(nodePaths)}`)
            if(nodePaths.length === 0){
              console.log(`::warning::No changes found, release will be skipped.`)
            }
            console.log(`::set-output name=nodePaths::${JSON.stringify(nodePaths)}`);

  release-pr:
    runs-on: ubuntu-latest
    needs: changeFinder
    if: ${{ fromJson(needs.changeFinder.outputs.nodePaths)[0] != '' }}
    strategy:
      fail-fast: false
      matrix:
        package: ${{fromJson(needs.changeFinder.outputs.nodePaths)}}
    steps:
      - uses: google-github-actions/release-please-action@v2
        id: release-please
        with:
          path: packages/${{ matrix.package }}
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: ${{ matrix.package }}
          monorepo-tags: true
          command: release-pr
  release:
    runs-on: ubuntu-latest
    needs: changeFinder
    if: ${{ fromJson(needs.changeFinder.outputs.nodePaths)[0] != '' }}
    strategy:
      fail-fast: false
      matrix:
        package: ${{fromJson(needs.changeFinder.outputs.nodePaths)}}
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: tag-release
        with:
          path: packages/${{ matrix.package }}
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          monorepo-tags: true
          package-name: ${{ matrix.package }}
          command: github-release
      - uses: actions/checkout@v2
        if: ${{ steps.tag-release.outputs.release_created }}
      - name: Debug
        run: echo "${{ startsWith(steps.tag-release.outputs.tag_name, 'one') }}"
      - name: Deploy API
        if: ${{ steps.tag-release.outputs.release_created && matrix.package == 'two' }}
        run: echo "deploy"
